<a href="https://colab.research.google.com/github/OlehVakulchyk/DataScience/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [15]:
import numpy as np

a = np.linspace(1, 10, num=10, dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [16]:
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [27]:
import numpy as np

a = np.random.randint(1, 10, (5, 5))
print(a)

[[4 3 3 3 6]
 [8 6 4 1 3]
 [9 2 4 1 1]
 [1 3 6 8 7]
 [2 2 9 7 2]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [29]:
import numpy as np

a = np.random.random((4, 4))
print(a)

[[0.013202   0.44164534 0.70072888 0.64212228]
 [0.91356747 0.57190757 0.93352604 0.66826208]
 [0.30125952 0.31961279 0.37730184 0.18743907]
 [0.79492176 0.01734765 0.56347791 0.00356229]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [31]:
import numpy as np

a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(a, b, sep='\n')
print(a + b)
print(a - b)
print(a * b)

[7 3 6 5 3]
[9 5 1 4 6]
[16  8  7  9  9]
[-2 -2  5  1 -3]
[63 15  6 20 18]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [32]:
import numpy as np

a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(a, b, sep='\n')
print(np.dot(a, b))

[9 9 4 9 2]
[8 2 4 8 5]
188


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [34]:
import numpy as np

a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 3))
print(a, b, sep='\n')
print(np.dot(a, b))

[[3 1]
 [9 7]]
[[8 1 3]
 [3 6 1]]
[[27  9 10]
 [93 51 34]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [36]:
import numpy as np

a = np.random.randint(1, 10, (3, 3))
print(a)
print(np.linalg.inv(a))
print(np.dot(a, np.linalg.inv(a)))

[[3 6 1]
 [6 6 8]
 [6 8 9]]
[[ 0.18518519  0.85185185 -0.77777778]
 [ 0.11111111 -0.38888889  0.33333333]
 [-0.22222222 -0.22222222  0.33333333]]
[[ 1.00000000e+00 -2.49800181e-16  1.66533454e-16]
 [ 0.00000000e+00  1.00000000e+00  4.44089210e-16]
 [ 1.11022302e-16 -5.82867088e-16  1.00000000e+00]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [37]:
import numpy as np

a = np.random.random((4, 4))
print(a)
print(a.T)

[[0.83563934 0.45296422 0.89127492 0.84045814]
 [0.55892447 0.6389013  0.00911419 0.67647488]
 [0.65731995 0.82088721 0.67335992 0.96324888]
 [0.06631963 0.96871568 0.32358012 0.11743305]]
[[0.83563934 0.55892447 0.65731995 0.06631963]
 [0.45296422 0.6389013  0.82088721 0.96871568]
 [0.89127492 0.00911419 0.67335992 0.32358012]
 [0.84045814 0.67647488 0.96324888 0.11743305]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [39]:
import numpy as np

a = np.random.randint(1, 10, (3, 4))
b = np.random.randint(1, 10, 4)
print(a, b, sep='\n')
print(np.dot(a, b))

[[4 7 7 1]
 [4 1 5 5]
 [9 6 5 2]]
[5 8 1 8]
[ 91  73 114]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [41]:
import numpy as np

a = np.random.random((2, 3))
b = np.random.random(3)
print(a, b, sep='\n')
print(np.dot(a, b))

[[0.20314678 0.93921513 0.38418054]
 [0.9227414  0.87240721 0.82884044]]
[0.62026912 0.932425   0.56191242]
[1.21762915 1.85153802]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [43]:
import numpy as np

a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(a, b, sep='\n')
print(a * b)

[[9 5]
 [8 6]]
[[6 5]
 [8 5]]
[[54 25]
 [64 30]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [44]:
import numpy as np

a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(a, b, sep='\n')
print(np.dot(a, b))

[[9 6]
 [5 3]]
[[4 6]
 [3 7]]
[[54 96]
 [29 51]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [45]:
import numpy as np

a = np.random.randint(1, 100, (5, 5))
print(a)
print(a.sum())

[[31 47 83  6 18]
 [23  4 54 79 32]
 [ 9 51 81 60 64]
 [12 19 57 92 43]
 [98 16 66 92  5]]
1142


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [46]:
import numpy as np

a = np.random.randint(1, 10, (4, 4))
b = np.random.randint(1, 10, (4, 4))
print(a, b, sep='\n')
print(a - b)

[[1 8 6 2]
 [7 7 8 2]
 [5 2 9 6]
 [9 2 7 8]]
[[9 7 1 2]
 [9 8 4 7]
 [3 6 6 4]
 [7 5 7 8]]
[[-8  1  5  0]
 [-2 -1  4 -5]
 [ 2 -4  3  2]
 [ 2 -3  0  0]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [47]:
import numpy as np

a = np.random.random((3, 3))
b = np.ones((3,), dtype=int)
print(a, b, sep='\n')
print(np.dot(a, b).T)

[[0.37665698 0.50028253 0.85988817]
 [0.63867482 0.19992611 0.46861755]
 [0.59862685 0.39046315 0.66041759]]
[1 1 1]
[1.73682767 1.30721848 1.64950759]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [48]:
import numpy as np

a = np.random.randint(1, 100, (3, 4))
print(a)
print(a * a)

[[10 65 67 19]
 [47 40 31  8]
 [31 11 16 52]]
[[ 100 4225 4489  361]
 [2209 1600  961   64]
 [ 961  121  256 2704]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [50]:
import numpy as np

a = np.random.randint(1, 50, 4)
print(a)
print(np.sqrt(a))

[13  5 43 46]
[3.60555128 2.23606798 6.55743852 6.78232998]
